In [59]:
import numpy as np

Adj=np.zeros((4,4))

Adj[0][1]=0.5
Adj[0][2]=0.25
Adj[0][3]=0.25
Adj[1][0]=0.667
Adj[1][2]=0.333
Adj[2][0]=0.333
Adj[2][1]=0.333
Adj[2][3]=0.333
Adj[3][0]=0.5
Adj[3][2]=0.5

eigvals,V = np.linalg.eig(Adj)

V2 = V[:, :][:, [0,3]]

sM = np.zeros((2,4)) 
sM2 = np.zeros((2,4)) 
sM3 = np.zeros((2,4)) 
sM4 = np.zeros((2,4)) 
sM5 = np.zeros((2,4)) 
sM6 = np.zeros((2,4)) 


sM[0][0] = 1
sM[1][1] = 1

sM2[0][0] = 1
sM2[1][2] = 1

sM3[0][0] = 1
sM3[1][3] = 1

sM4[0][1] = 1
sM4[1][2] = 1

sM5[0][1] = 1
sM5[1][3] = 1

sM6[0][2] = 1
sM6[1][3] = 1

#print(sM,"\n\n",sM2,"\n\n",sM3,"\n\n",sM4,"\n\n",sM5,"\n\n",sM6)

C = np.dot(sM,V2)
C2 = np.dot(sM2,V2)
C3 = np.dot(sM3,V2)
C4 = np.dot(sM4,V2)
C5 = np.dot(sM5,V2)
C6 = np.dot(sM6,V2)

u, s, vh = np.linalg.svd(C, full_matrices=True)
u2, s2, vh2 = np.linalg.svd(C2, full_matrices=True)
u3, s3, vh3 = np.linalg.svd(C3, full_matrices=True)
u4, s4, vh4 = np.linalg.svd(C4, full_matrices=True)
u5, s5, vh5 = np.linalg.svd(C5, full_matrices=True)
u6, s6, vh6 = np.linalg.svd(C6, full_matrices=True)

print(np.min(s)
,np.min(s2)
,np.min(s3)
,np.min(s4)
,np.min(s5)
,np.min(s6))

sM5

0.20334169877334676 0.3196711215892757 0.5129901622253884 0.5325246349417662 0.6848863587931393 0.23717810905212208


array([[0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [33]:
import numpy as np
Adj=np.zeros((2,3))

Adj[0][0]=1
Adj[0][1]=2
Adj[0][2]=3
Adj[1][0]=4
Adj[1][1]=5
Adj[1][2]=6

Aux=np.zeros((3,1))

u, s, vh = np.linalg.svd(Aux, full_matrices=True)

In [4]:
from itertools import combinations 
import numpy as np
import operator

A=np.zeros((4,4))

A[0][1]=0.5
A[0][2]=0.25
A[0][3]=0.25
A[1][0]=0.667
A[1][2]=0.333
A[2][0]=0.333
A[2][1]=0.333
A[2][3]=0.333
A[3][0]=0.5
A[3][2]=0.5

eigvals,V = np.linalg.eig(A)
### trocar len(A) por len(V2) ... para o input só precisa de M e de V2
###
Ve = V[:, :][:, [0,3]]
###

M = 2

def optimal_sampling_operator(M,V2):
    a = np.zeros((1,len(V2)))
    b = np.zeros((len(V2),len(V2)))

    for j in range(len(V2)):
        a[0,j] = 1
        b[j] = a
        a = np.zeros((1,len(V2)))

    cb = np.arange(len(V2))
    comb = combinations(cb, M)
    len_ = len(list(combinations(cb, M)))

    Psi = np.zeros((len_,M,len(V2)))

    k = 0
    for i in list(comb):
        Psi[k] = [b[i[0]],b[i[1]]]
        k = k + 1

    lst = []
    for i in range(k):
        C = np.dot(Psi[i],V2)
        u, s, vh = np.linalg.svd(C, full_matrices=True)
        lst.append(np.min(s))

    index, value = max(enumerate(lst), key=operator.itemgetter(1))

    return (Psi[index])

R = optimal_sampling_operator(2,Ve)
R

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [40]:
from itertools import combinations 
import numpy as np
import operator

A=np.zeros((4,4))

A[0][1]=0.5
A[0][2]=0.25
A[0][3]=0.25
A[1][0]=0.667
A[1][2]=0.333
A[2][0]=0.333
A[2][1]=0.333
A[2][3]=0.333
A[3][0]=0.5
A[3][2]=0.5

eigvals,V = np.linalg.eig(A)
### trocar len(A) por len(V2) ... para o input só precisa de M e de V2
###
Ve = V[:, :][:, [0,3]]
###

M = 2

def optimal_sampling_operator(M,V2):
    a = np.zeros((1,len(V2)))
    b = np.zeros((len(V2),len(V2)))

    for j in range(len(V2)):
        a[0,j] = 1
        b[j] = a
        a = np.zeros((1,len(V2)))

    cb = np.arange(len(V2))
    comb = combinations(cb, M)
    len_ = len(list(combinations(cb, M)))

    Psi = np.zeros((len_,M,len(V2)))

    k = 0
    for i in list(comb):
        for j in range(M):
            Psi[k][j] = b[i[j]]
        k = k + 1

    lst = []
    for i in range(k):
        C = np.dot(Psi[i],V2)
        u, s, vh = np.linalg.svd(C, full_matrices=True)
        lst.append(np.min(s))

    index, value = max(enumerate(lst), key=operator.itemgetter(1))

    return (Psi[index])

R = optimal_sampling_operator(2,Ve)
R

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [33]:
Psi = np.zeros((6,3,len(Ve)))
#Psi[0] = [[1,1,1,1],[1,1,1,0],[1,1,0,1]]
Psi[0][0] = [1,1,1,1]

In [34]:
Psi[0]

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])