In [169]:
def optimal_sampling_operator_greedy_algorithm(M,V2):

    import numpy as np
    import operator

    lst = []
    Psi = np.zeros((M,len(V2)))
    a = np.zeros((1,len(V2)))
    b = np.zeros((len(V2),len(V2)))
    V = V2
    
    for j in range(len(V2)):
        a[0,j] = 1
        b[j] = a
        a = np.zeros((1,len(V2)))
    
    k = 0
    while k < M:
        for i in range(len(V2)):
            u, s, vh = np.linalg.svd([V2[i]], full_matrices=True)
            lst.append(np.min(s))

        index, value = max(enumerate(lst), key=operator.itemgetter(1))
        ind = np.where((V == V2[index]).all(axis=1))
        V2 = np.delete(V2, (index), axis=0)
        Psi[k] = b[ind[0]]
        k=k+1
        lst = []
    
    return(Psi)

In [170]:
import numpy as np
import operator

Adj=np.zeros((4,4))

Adj[0][1]=0.5
Adj[0][2]=0.25
Adj[0][3]=0.25
Adj[1][0]=0.667
Adj[1][2]=0.333
Adj[2][0]=0.333
Adj[2][1]=0.333
Adj[2][3]=0.333
Adj[3][0]=0.5
Adj[3][2]=0.5

eigvals,V = np.linalg.eig(Adj)

V2 = V[:, :][:, [0,3]]

a = np.zeros((1,len(V2)))
b = np.zeros((len(V2),len(V2)))

Psi = np.zeros((M,len(V2)))

for j in range(len(V2)):
    a[0,j] = 1
    b[j] = a
    a = np.zeros((1,len(V2)))

V2 = V[:, :][:, [0,3]]
lst = []
M = 2
m = np.zeros((M,len(V2)))
k = 0
while k < M:
    for i in range(len(V2)):
        u, s, vh = np.linalg.svd([V2[i]], full_matrices=True)
        lst.append(np.min(s))

    index, value = max(enumerate(lst), key=operator.itemgetter(1))
    V2 = np.delete(V2, (index), axis=0)
    m[k] = b[index]
    k=k+1
    lst = []
    
print(m)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [171]:
import numpy as np
import operator

Adj=np.zeros((4,4))

Adj[0][1]=0.5
Adj[0][2]=0.25
Adj[0][3]=0.25
Adj[1][0]=0.667
Adj[1][2]=0.333
Adj[2][0]=0.333
Adj[2][1]=0.333
Adj[2][3]=0.333
Adj[3][0]=0.5
Adj[3][2]=0.5

eigvals,V = np.linalg.eig(Adj)

V2 = V[:, :][:, [0,3]]

P = optimal_sampling_operator_greedy_algorithm(2,V2)
print(P)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [172]:
C = np.ones((1,4))

V[2][0] = 1
V[2][1] = 1
V[2][2] = 1
V[2][3] = 1

ind = np.where((C == V[2]).all(axis=1))
ind[0]

array([0])